# Generated by Django 3.0 on 2020-07-07 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid username', message='username must be AlphaNumeric', regex='^[a-zA-Z0-9.+-]*$')]),
        ),
    ]
